// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW_kowFxem14--YEIZ66rhySyBe9ooVfw',
    appId: '1:117049398055:web:7823fdcb73668f7a37cf02',
    messagingSenderId: '117049398055',
    projectId: 'ariareads-dal',
    authDomain: 'ariareads-dal.firebaseapp.com',
    storageBucket: 'ariareads-dal.appspot.com',
    measurementId: 'G-1HJFKYW1WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Z5rXAONiQR7uhjNc5cOUYDgpDklHIvo',
    appId: '1:117049398055:android:a607ebab34270bec37cf02',
    messagingSenderId: '117049398055',
    projectId: 'ariareads-dal',
    storageBucket: 'ariareads-dal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZI_zyc9CkMq1n_4JI6oPCC4uFsC1v8Q',
    appId: '1:117049398055:ios:167d229389f1862837cf02',
    messagingSenderId: '117049398055',
    projectId: 'ariareads-dal',
    storageBucket: 'ariareads-dal.appspot.com',
    iosClientId: '117049398055-f6865bl504q8rt7g469273vj76gevp1l.apps.googleusercontent.com',
    iosBundleId: 'com.ariareads.dal.ariareads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdZI_zyc9CkMq1n_4JI6oPCC4uFsC1v8Q',
    appId: '1:117049398055:ios:167d229389f1862837cf02',
    messagingSenderId: '117049398055',
    projectId: 'ariareads-dal',
    storageBucket: 'ariareads-dal.appspot.com',
    iosClientId: '117049398055-f6865bl504q8rt7g469273vj76gevp1l.apps.googleusercontent.com',
    iosBundleId: 'com.ariareads.dal.ariareads',
  );
}
